### ISSUE TITLE
possibly unknown origin place and date

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#1]
I replaced them with "unknown" for now. But they need to be checked. 

xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.15a.xml
Description: <date notBefore="0001" notAfter="0002">xx</date>
Description: <placeName ref="xx">xx</placeName>

xml_inscriptions/transcribed/MI.AA.UM.KM.L.1567.xml
Description: <placeName ref="xx">xx</placeName>

xml_inscriptions/transcribed/MI.AA.UM.KM.L.6808.xml
Description: <date notBefore="0001" notAfter="0002">xx</date>
Description: <placeName ref="xx">xx</placeName>

xml_inscriptions/transcribed/MI.AA.UM.KM.L.93880and93894and93896and1966.2.3--unpublished.xml
Description: <date notBefore="0001" notAfter="0002">xx</date>
Description: <placeName ref="xx">xx</placeName>

**Comment by sdigiulio** [comment]
Corrected KM.1567 and 6808 based on the information contained in Tuck, will check the other two against other hard copy information.

**Comment by sdigiulio** [comment]
Checked and confirmed all against paper files, edited xml accordingly.
