### ISSUE TITLE
MA.Well.WC display problems

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#10]
None of the recent batch of inscriptions in MA.Well.WC are displaying, and the collection returns a 500 error. I've already checked ms id nos and reconciled those, and I've been trying to locate the remaining errors to get everything to display, though the xml is valid (other than <biblScope type= > instead of <biblScope unit= >, which I think we haven't implemented yet anyway. At this point I'm fairly sure the xml is clear of errors, but will keep looking.

**Comment by emylonas** [comment]
one possibility: could it be that we are using zxx for the language attribute value? It stands for non-linguistic content, but I don't think we use it anywhere else. It might be upsetting the indexing.

You can view the solr index here: 
http://library.brown.edu/search/solr_pub/usep/?rows=20&facet=true&facet.limit=1000&facet.mincount=1&start=0&facet.field=bib_ids&f.bib_ids.facet.sort=false&facet.field=bib_ids_filtered&f.bib_ids_filtered.facet.sort=false&facet.field=bib_titles&f.bib_titles.facet.sort=false&facet.field=condition&f.condition.facet.sort=false&facet.field=decoration&f.decoration.facet.sort=false&facet.field=fake&f.fake.facet.sort=false&facet.field=text_genre&f.text_genre.facet.sort=false&facet.field=language&f.language.facet.sort=false&facet.field=material&f.material.facet.sort=false&facet.field=msid_region&f.msid_region.facet.sort=false&facet.field=msid_settlement&f.msid_settlement.facet.sort=false&facet.field=msid_institution&f.msid_institution.facet.sort=false&facet.field=msid_repository&f.msid_repository.facet.sort=false&facet.field=object_%20type&f.object_type.facet.sort=false&facet.field=status&f.status.facet.sort=false&facet.field=writing&f.writing.facet.sort=false&q=%2A%3A%2A&fq=msid_region%3A%22MA%22&fq=msid_settlement%3A%22Well%22&fq=msid_institution%3A%22WC%22&sort=&wt=json&json.nl=arrarr

**Comment by emylonas** [comment]
It looks as if MA.Well.WC.L.Tmp97.3.2 does not appear in SOLR. Also, it is the only file that isn't validating - it's complaining about the biblScope/@type, which is also in the other files. It's possible if the other files were already there that they might not have been re-indexed? But this is something that lots of our files have. You could try changing them all to "unit" and see if something happens. But that might break the indexing.

**Comment by emylonas** [comment]
OK, MA.Well.WC.L.Tmp.3.2 does not have the schema declaration at the top of the file commented out. All the others that I looked at had it commented out, so they are not complaining at the incorrect @type attribute. This one is validating against a real schema and failing. You could test by commenting out the schema decl. also check the others to see if there are any more that are similar. No idea why we are doing this. It means we aren't validating properly.

**Comment by sdigiulio** [comment]
I removed the commenting out of the schema (which is in the newest version of the template that I've been using when I work, I just checked), as well as getting rid of the xml:lang="zxx" (changed them to "lat" for now), and individual inscriptions are all displaying at their direct url - . Still getting a 500 error, indexing still thinks there are "zxx" values for the inscriptions that I removed them from.

**Comment by emylonas** [comment]
commenting shouldn't be a problem. the xml:lang might be but again, don't
know why. I'll ask about that. spent time on that last night. global
changes tonight or early tomorrow. --elli

**Comment by sdigiulio** [comment]
xml:lang="zxx" wasn't being handled properly, was breaking the indexing. Changed the code to "lat", is indexing fine now but we should consider setting up to process the non-linguistic language code zxx.
