### ISSUE TITLE
Revisions to Author Display

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#104]
Need to smooth out the way we display authors; would like to add two separate categories, one for author specifically and one for editors. Will need to set up specific references/control vocab for these particular author categories. Connected to #34 and #55.

**Comment by emylonas** [comment]
This is also related to #99 - need to normalize names

**Comment by sdigiulio** [comment]
@jbodel's comments on #127: 
"Upon reflection, I don't think the auto-generated author line works. I think we need to have this data entered manually, because each case will require its own human decisions about credit and order of listing. All names will also need to be spelled out.

The default reading should be blank rather than the current "CDS on: 2010-09-29", which can only be mystifying to outsiders and even internally (as we know) does not means what it seems to indicate: "CDS" did not author any entries."

@emylonas I think we can do this by adding author to the responsibility statements at the head? But someone will have to make the call as to who gets what level of credit, and we'll need to put our heads together on how to get that to display.

**Comment by sdigiulio** [comment]
One potential solution is to add a `<respStmt>` to the existing `<titleStmt>`, so that you get something that looks like the following:
`<titleStmt>
  <title>AB.CD.EFG.L.12345</title>
  <respStmt>
     <name role="author" when="2021-03-09">John Q. Author</name>
     <name role="editor" when="2021-03-10">John Doe Editor</name>
  </respStmt>
</titleStmt>`

Assignation of `@role` would have to be done by project manager or project director. usep_display.xsl should be able to be modified to show the data here in a relatively straightforward manner.

**Comment by emylonas** [comment]
Some further options:

- Add an `<author>` element for the "main" author, right after `<title>`
- Add a series of `<respStmt>`s after the author. Each `<respStmt>` will pertain to a specific div, for ex. translation, commentary, transcription. The `<respStmt>` will contain one or more names of people who worked on that part of the inscription.

```
<titleStmt>
<title>AB.CD.EFG.L.12345</title>
<author>Jane Classicist</author>
<respStmt>
   <name>Fred Student</name>
   <name when="2021-03-09">Mary Student</name>
   <resp>commentary</resp>
</respStmt>
<respStmt n="translation">
   <name when="2021-03-09">John Q. Author</name>
</respStmt>

</titleStmt>
```
- Alternatively, a series of `<respStmt>`s each of which contains a name and a resp

```
<titleStmt>
<title>AB.CD.EFG.L.12345</title>
<author>Jane Classicist</author>
<respStmt>
   <name>Fred Student</name>
   <resp>commentary</resp>
</respStmt>
<respStmt>
   <name when="2021-03-09">Mary Student</name>
   <resp>updated commentary</resp>
</respStmt>
<respStmt>
   <name when="2021-03-09">John Q. Author</name>
  <resp>translation</resp>
</respStmt>

</titleStmt>
```

**Comment by sdigiulio** [comment]
Added to all files in 35dc0b81c3907a0bdef3dc78d0b3eb02ac0af367; all that's needed now is to populate and @sdigiulio will write the display XSLT.
