### ISSUE TITLE
inscriptions with more than one image only display first one

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#108]
for ex. https://usepigraphy.brown.edu/projects/usep/inscription/MD.Balt.WAG.G.47.55/ has two images, but only one shows up in the upper left of the inscription view.

**Comment by sdigiulio** [comment]
I'm pretty sure the issue here is a missing image file, not an issue in the XSL Other inscriptions with multiple images are working fine (e.g. https://usepigraphy.brown.edu/projects/usep/inscription/CA.Malibu.JPGM.G.77.AA.33/)
