### ISSUE TITLE
attribute display is too narrow

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#109]
Causing metadata values to break over more than one line. this is caused by css that is added at the top of the inscription HTML before the SaxonCE transformation is inserted.

Figure out why we are doing it in this place and not in global css. Change the widths in the right place.

**Comment by emylonas** [comment]
This is specified in https://github.com/Brown-University-Library/usepweb_project/blob/master/usep_app/usep_templates/display_inscription.html l.66

```
https://github.com/Brown-University-Library/usepweb_project/blob/master/usep_app/usep_templates/display_inscription.html
```

**Comment by emylonas** [comment]
Remade this issue over in the code repository. It's Brown-University-Library/usepweb_projects#55

**Comment by sdigiulio** [comment]
Completed in 3ca2a9e; closing.
