### ISSUE TITLE
New Category: Object History

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#111]
this category to replace the two entries now existing for “Subsequent location”
and “Acquired”. In encoding the metadata we will still want to note all the same aspects --
acquired how, when, by whom, from whom, for whom --within the synthetic object history]

**Comment by jbodel** [comment]
My idea for the best ordering of our metadata categories is:

Inscription Type	
Object Type	
Material	
Writing	
Layout
Decoration
Condition
Place of Origin
Object history  [in encoding the metadata we will still want to note all the same aspects -- acquired how, when, by whom, from whom, for whom --within the synthetic object history]
Date (of inscription)
Dating criteria (one or more, as chosen from controlled vocab)
