### ISSUE TITLE
Reformulate "Date" Category and add new infromation

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#112]
Dating criteria [this is a new category, to be populated by one or more of a short set of fixed
terms chosen perhaps from a pull-down menu: I think we can follow the existing categories used
by EDR and EDH, as follows:
* archaeology = find context or object type or form (art historical aspects)
* formulae = textual formulae or modes of expression, including symbols (e.g. chi rho, “HS” for
“sesterces” etc.)
* history = reference to historically datable phenomena (e.g. reigns, territorial names)
* institutions = reference to historically datable institutions (e.g. ephebeia, Augustales)
* prosopography = the text mentions persons known and datable (magistrates, rulers)
* nomenclature = the text records onomastic features datable to a certain era
* language = the text exhibits linguistic features datable to a particular era (vocalic shifts, B for V)
* paleography = scriptural features (3 bar sigmas, letter forms

This will require additions to the schema, authoring form and display

**Comment by emylonas** [comment]
This is related to  #59

**Comment by sdigiulio** [comment]
Categories added to control vocab in d5525dc926b17b9cc6d69d93cdb9f1d40cdd2f71.

**Comment by emylonas** [comment]
The markup for this feature, based on the Epidoc Guidelines, is `<date notBefore... notAfter... evidence="archaeological">the date goes here</date>` and the values that John lists above are added to the `@evidence` attribute. 
In order to handle older inscriptions more easily, and also to assist if the inscriptions are being edited in github, would it make sense to add that attribute to all existing inscriptions with a date element? If so, we will need to have a value such as `unspecified` or `undetermined` as a placeholder. This value need not be displayed on an inscription web page. 

Quesion for @jbodel : Is it ok to add such a value to our list. It will be the default value, and will not be displayed. You can then more easily edit an inscription and replace that word with the correct value. If it's ok, what value do you prefer? `unspecified`, `undetermined` ? other?

**Comment by jbodel** [comment]
Yes, good idea. Eventually all dates should be systematically checked, corrected where needed, and dating criteria added (by me or someone else knowledgeable about this tricky part of epigraphy). If it is allowed, I think the best term for the default (no-show) value would be "unknown". Otherwise "unspecified" is preferable to "undetermined".

**Comment by sdigiulio** [comment]
I've added values to the vocabulary for both 'unknown' and 'unspecified'; we can choose which we'd prefer and add that into the default template.

**Comment by emylonas** [comment]
@emylonas or @sdigiulio should modify existing files with the favored unspecified/unknown value. will be done for April May
@emylonas should add to the template and Oxygen forms. Summer.

**Comment by sdigiulio** [comment]
All files have `@evidence` added to them. Still needs: 
1. data updates and corrections 
1. xsl to display on page
1. incorporation into template

**Comment by emylonas** [comment]
This has been added to the Author template. Needs to be added to the display.

Also, the attribute value has to have a # in front of it, otherwise the author drop-down doesn't work.

**Comment by sdigiulio** [comment]
Updated xsl added to website in #167; everything should now be complete for this.
