### ISSUE TITLE
Add support for "ett" lang code

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#113]
Now that we are adding Etruscan inscriptions to database, need to fix the way that these display when they are indexed and sorted. Currently showing up only as "ett" in search.

**Comment by sdigiulio** [comment]
Connects to #172; @emylonas, is this handled in the xsl or in elsewhere in the project code?

**Comment by emylonas** [comment]
This is being handled in the project code. See production repository [issue 59](https://github.com/Brown-University-Library/usepweb_project/issues/59). Closing
