### ISSUE TITLE
ITA.Rome.AAR file nos ending in numbers under 400 are not loading, need to be renumbered according to AAR inv. no rather than Babcock catalog nos.

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#117]

**Comment by emylonas** [comment]
This has been fixed - the only inscriptions that should be showing up are those with USEP numbers over 400. The inscriptions origingally encoded with Babcock numbers have been renames to AAR inventory numbers. The reason the Babcock numbers were showing up is that they were not purged from the Solr index. Delete Orphans is now in place and the orphans have been removed.  Closing
