### ISSUE TITLE
ITA.Rome.AAR images still not loading or missing 

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#119]
In list 2 of 49 (only) show "No image available" icon. We have images with labels for all or nearly all -- need to be uploaded to Github repository and/or re-linked.

**Comment by sdigiulio** [comment]
I'm pretty sure the missing images were all (or at least mostly) addressed in ec8eb6e9d70a07feb369674c8efd535fa37db4f0, so I'll close this issue.
