### ISSUE TITLE
Framework schema and schemas in XML files not the same. 

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#12]
The framework is using the svn latest (which doesn't work) and the files have a cds.library.brown.edu URL. All should be 
http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng

**Comment by sdigiulio** [comment]
@emylonas there haven't seemed to be any issues on this front, right? If not, I'll close the issue.

**Comment by sdigiulio** [comment]
All good here, and I don't think anything has changed since the last update; closing the issue.
