### ISSUE TITLE
Adding Translations to inscriptions (<div type="translation"> )

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#122]
The project would like to have translations for the inscriptions. Currently, 97 inscriptions have a translation. The other "Transcribed" inscriptions do not have a placeholder for the translation. 

Currently the template includes `<div>`s for transcription and commentary. They appear on the inscription web page whether they have content or not. I have found a few that say "notes here".  

We can update the template to add a div for translation as well. New inscriptions would have a translation, and we can add a button in the author mode to delete it. This should also be done for commentary.

Alternatively, we could add buttons for adding commentary and adding a translation.

To edit directly in github, it may be best to paste in the whole code snippet and then fill in the translation. 

For existing inscriptions,

**Comment by jbodel** [comment]
I follow about direct editing in Github but am not sure what the alternatives are about for <div> elements or buttons. Buttons would point to a div element wouldn't' they?

**Comment by sdigiulio** [comment]
The question with buttons is whether we include them in the Author mode to provide a `<div>`, with the relevant type populated, when an encoder wants to put it in, or if we include those parts by default in any new file. If we do include them in any new files by default, we'll probably want to do some rewriting of the xsl to avoid showing blank fields if people don't provide such information.

**Comment by jbodel** [comment]
O.K. Thanks. I think we DO want them in by default, since eventually every inscription should have one. Our current template has several metadata categories that are not always filled, and it does not look bad.

**Comment by emylonas** [comment]
Add translation divs to all inscriptions that don't already have one. Note that there already there 97 files that have a translation div in them.

**Comment by emylonas** [comment]
All transcribed inscriptions have necessary divs. These are not in place in metadata only or bib only inscriptions. Do we want to add to the files that only have metadata?

**Comment by jbodel** [comment]
Yes, we do. And wherever we have a transcription div, we should now also have a translation div.

**Comment by emylonas** [comment]
all metadata only inscriptions have the necessary divs with b07a407

closing
