### ISSUE TITLE
encoding instructions in template need editing

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#125]
In our USEP template, some of the verbal instructions to encoders need to be edited. I can do this myself if I have access to change/edit the text. Otherwise I can pass along individual places for updating. As, for example, in the following set of instructions, in which the word "fake" should in every case be replaced by "modern" (corresponding to our new designation "-mdn" in USEP nos.) and the last word "real" should be replaced by "ancient". Also, "USEp." can be replaced throughout with "USEP".

**Comment by emylonas** [comment]
Easiest is to send you a copy of the template, as it's all bundled up with
our framework in Git. Scott and I were talking about some of the wording,
including changing "fake". Once it's settled, we can make global changes to
existing comments. --elli

**Comment by emylonas** [comment]
oxygen framework template is in this directory on github:
https://github.com/Brown-University-Library/usep-data/tree/master/oxygen-author/usep-forms2.0/templates

**Comment by emylonas** [comment]
@jbodel @sdigiulio I am working on the Author templates. In the History section, we have a pulldown menu with the values "Fake" and "Genuine" What should I change them to? "Ancient" "Modern" ?  We are using Modern as our term for _falsa vel aliena_ but I'm not sure what the default term should be. 

Also, once this value is changed, we have to change the display XSL.

**Comment by jbodel** [comment]
Yes, "ancient" and "modern" are (I think) the best terms to use--
least prejudicial. Also, these make easier a distinction between
object and inscribed text, where relevant -- issue 125. Thanks!

**Comment by emylonas** [comment]
Done:

1. changed existing "fake" to "modern" (except for3 noted below)
1.  added correct terms to template and Author mode

Remaining:
1. xslt to look for "modern" and not "fake" when formatting
2. Adjust search to use "modern" (when it is worked on)
2.  3 inscriptions have an  `<rs>` say "probably fake" and so won't be noticed as the expected values are `modern` (formerly fake) and `ancient`. perhaps John or Scott can take a look at decide what to say there. 
NY.NY.CU.Butl.L.49
IL.Chi.AIC.L.1926.621
IL.Chi.AIC.G.1889.26

**Comment by jbodel** [comment]
NY.NY.CU.Butl.L.49 is genuine: date 0-100 based on arch., onomastics
IL.Chi.AIC.L.1926.621 is also genuine, but uninscribed: date 0-120 based on arch
IL.Chi.AIC.G.1889.26: I can't tell; no photo available. The object sounds odd--painted terracotta with gilt lettering? --but the text is plausible. The presumed date of accession (1889) makes it more plausible as a genuine find from Tarentum. Best to leave as "ancient" for now.

**Comment by sdigiulio** [comment]
Fixed the three inscriptions mentioned here in https://github.com/Brown-University-Library/usep-data/commit/f95c46c08ab1a56b02e4260a30ae46eb4fdbf89e; once the last revisions to the values in the Author mode are complete, this can be closed.

**Comment by sdigiulio** [comment]
My understanding is that the newest version of the template has made these changes, so I'll close this issue; we can reopen if needed, though.
