### ISSUE TITLE
"Author" credit line fix

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#127]
Upon reflection, I don't think the auto-generated author line  works. I think we need to have this data entered manually, because each case will require its own human decisions about credit and order of listing. All names will also need to be spelled out. 

The default reading should be blank rather than the current "CDS on: 2010-09-29", which can only be mystifying to outsiders and even internally (as we know) does not means what it seems to indicate: "CDS" did not author any entries.

**Comment by sdigiulio** [comment]
This is a continuation of #99 and #104; moving the discussion onto #104. In the meantime, I'll disable the existing author display.
