### ISSUE TITLE
TN.Mem.MBMA - a new collection to add

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#130]
A new collection to add:

Memphis Brooks Museum of Art
1934 Poplar Avenue, 
Memphis, TN 38104
901.544.6200 
pr@brooksmuseum.org
Link to museum Collections homepage: http://emuseum.brooksmuseum.org/collections

Here is a blurb for the Collections page:

The Memphis Brooks Museum of Art houses a small collection of objects from the ancient Mediterranean and Near East, including an inscribed Athenian grave relief of the fourth or third century BCE and an inscribed limestone funerary stele from Egypt of the third or fourth century CE, both on long-term loan from the Clarence Day Foundation.

**Comment by gaiagianni** [comment]
Added
