### ISSUE TITLE
TN.Mem.MBMA.G.LI.90.3 and TN.Mem.MBMA.G.LI.90.18

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#131]
Here attached are folders with information to make entries for the 2 inscriptions in the new TN.Mem.MBMA collection. The first, TN.Mem.MBMA.G.LI.90.3, is based on information helpfully supplied by UGa Art History grad. student Holly Bostock, whose query about that monument provides useful info. also on similar inscriptions from  GA.Atl.EU.MCM, MA.Bos.MFA and NY.NY.MMA, which I have broken out into separate files and will send separately

For TN.Mem.MBMA.G.LI.90.3, please: 1) enter relevant data in all the right places: spreadsheet, USEP data file folder labelled by USEP no., paper folders in USEP office 2) label the photo (+ two "det." photos) and post them to depository and folders (TIFF, jpg, and original); 3) enter metadata and transcription and translation (using my text file for the last two: if you want to take a crack at the second name, please do: see my notes and the photo). 

For TN.Mem.MBMA.G.LI.90.18 I have only made pdfs of the museum files I found online and have not transcribed the inscription. Please enter at least metadata for it.

[TN.Mem.MBMA.G.LI.90.3.zip](https://github.com/Brown-University-Library/usep-data/files/4340897/TN.Mem.MBMA.G.LI.90.3.zip)
[TN.Mem.MBMA.G.LI.90.18.zip](https://github.com/Brown-University-Library/usep-data/files/4340898/TN.Mem.MBMA.G.LI.90.18.zip)

**Comment by gaiagianni** [comment]
Done. Files in the pull request and images added to the repository.
