### ISSUE TITLE
NY.NY.MMA - new info for 2 existing entries: G.38.11.13 and G.57.42

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#132]
[NY.NY.MMA.zip](https://github.com/Brown-University-Library/usep-data/files/4340909/NY.NY.MMA.zip)

**Comment by gaiagianni** [comment]
Should I label the images you sent and add them to the repository? Are these subject to copyright?

**Comment by jbodel** [comment]
Yes, please and no, I don't think there are any copyright problems since the image is available in lower res jpg on the museum site. But I will check. We will want these images labelled in any case,  and go ahead and add them to the repository. If we need to pull them later we can, but I doubt we will. Thanks.

**Comment by gaiagianni** [comment]
Done.
