### ISSUE TITLE
GA.Atl.EU.MCM.G.1984.16 + MA.Bos.MFA.G.19.318 - new info. for existing entries

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#133]
[GA.Atl.EU.MCM.G.1984.16.docx](https://github.com/Brown-University-Library/usep-data/files/4340919/GA.Atl.EU.MCM.G.1984.16.docx)
[MA.Bos.MFA.G.19.318.docx](https://github.com/Brown-University-Library/usep-data/files/4340920/MA.Bos.MFA.G.19.318.docx)

**Comment by gaiagianni** [comment]
Done. Uploaded changes on github pull request.
