### ISSUE TITLE
dimensions type="letter" in wrong place

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#136]
A number of inscriptions put the letter dimensions inside the support element, following the object dimensions. Need to be moved to handnote.

**Comment by sdigiulio** [comment]
Most of this seems to stem from the first era in which we were trying to collect the data (a good chunk of it is my own work); I'll try to work on getting this information straightened out in advance of working on its display in #129.

**Comment by jbodel** [comment]
129/ 136 need to be incorporated also into the Encoder Instructions
