### ISSUE TITLE
HI.Honol.AA to become HI.Honol.HMA with new collection description + sole entry

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#138]
The institution changed its name in 2012 from Honolulu Academy of Arts (hence HI.Honol.AA) to Honolulu Museum of Arts. Since the collection description is wrong--there is no longer any Greek epitaph in the collection--only the collection entry needs to be changed and there are no entries to modify. Instead, there is a first new entry to add, attached here. 

Gaia, would you please make the change to collection ID and add the new entry (metadata, transcription, and translation--pretty easy!) and the collection description below, when you can?

HI.Honol.HMA

The Honolulu Museum of Art (until 2012, the Honolulu Academy of Arts) houses a small collection of classical antiquities, including the right side of a Roman floor mosaic of the third century CE depicting an Eros riding a dolphin surrounded by marine life and, spelled out in marble tesserae, the end of a dedication to [Aphro]dite. Said to have originated in Rome, the panel was donated to the Museum by Clare Booth Luce in 1983.

[HI.Honol.HMA.G.5110.1.pdf](https://github.com/Brown-University-Library/usep-data/files/4395577/HI.Honol.HMA.G.5110.1.pdf)

**Comment by gaiagianni** [comment]
Done.
