### ISSUE TITLE
TX.SA.SAMA and elsewhere - ordering of entries by language

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#147]
For some reason the inscriptions of this collection are listed in the order: Latin first, then "Undecided", then Greek. The correct / default order, for any collection that has inscriptions in more than one language, should be:
Greek - Latin - (Other; if more than 1, then alphabetically by language) - Undecided.

Sequence needs re-arranging here.

**Comment by emylonas** [comment]
I'll look into this - it's part of the production code. I'll check the exact location.

**Comment by jbodel** [comment]
Continuing data clean-up of language headings for individual Collections: 

PA.Phil.UP.UM - language heading "ETT" needs to be replaced with "ETRUSCAN"

**Comment by emylonas** [comment]
The May 7 comment has been handled with commit e3a2eeaf0b09c1910300f40e0bd4769ac4891bed. Language order is the same as #172 which is being handled in the production repository https://github.com/Brown-University-Library/usepweb_project/issues/59
