### ISSUE TITLE
MA.Glouc.HCM.L.03.8.10 - delete entire entry

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#148]
Everything about this one is wrong, starting with the USEP no. Not a stamp, not Latin (atextual). Best just to delete the entire file (and empty metadata filler)

**Comment by sdigiulio** [comment]
I'll go ahead and remove the file (and then close the ticket); if you can send me the correct information (if it exists), I'll put together the new file and upload it in it's place.
