### ISSUE TITLE
Validation error in older files

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#156]
Older files have an `<xi:include>` in the `<publicationStmt>`; this is getting flagged as invalid, even though it wasn't causing this issue recently. @emylonas, let me know what you think, but we may need to bulk-change all older `<publicationStmt>` elements to remove the old-style and match our newer files for validation purposes.

**Comment by emylonas** [comment]
Removed the include and replaced with `<authority>Brown University</authority>` with 4bead748
