### ISSUE TITLE
entry needs renumbering: MA.Glouc.HCM.L.Tmp97.6.15a 

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#163]
Change MA.Glouc.HCM.L.Tmp97.6.15a  to MA.Glouc.HCM.L.Tmp97.6.16-mdn. Also for photo of det. File + photos need relabeling

**Comment by sdigiulio** [comment]
I only see a 15-mdn and a 16 in the repository; I suspect this has been fixed and I will close the issue, but we can reopen if I'm mistaken.
