### ISSUE TITLE
xslt cleanup -- simple but major 

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#172]
In ALL collections, current order of data is Latin first then Greek. Order of presentation in all collections should be:

1. Greek
2. Latin
3. Other language(s) (if more than one, in chronological order of inscriptions held)

e.g. RI.Prov.RISD.MA currently lists inscriptions in the following puzzling order: Latin | Etruscan | Greek | Raetic
Should now be: Greek / Latin / Raetic / Etruscan

**Comment by sdigiulio** [comment]
This partially duplicates #147.

**Comment by emylonas** [comment]
This is being handled in the production code: https://github.com/Brown-University-Library/usepweb_project/issues/59

**Comment by emylonas** [comment]
fixed, closing
