### ISSUE TITLE
 RI.Prov.RISD.MA.Etr.31.364 has a phantom duplicate and broken photo link. 

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#174]

**Comment by jbodel** [comment]
Language code in USEP no. should be "E" not "ETR" universally

**Comment by sdigiulio** [comment]
We have no image for this object and hence it was left blank; I'll add a link to the image hosted on the RISD webpage in the meantime. 

My understanding was that we had settled on Etr as the code for USEP numbers a while a back, and @gaiagianni put together those various inscriptions based on that decision; if this has changed, though, we can go back and redo them.

**Comment by jbodel** [comment]
Hmmm, then maybe I am the one confused about the "ETR" (as the xml requires, I believe) and the single letter codes that we normally use. Certainly "Raet" makes sense for the rare "Raetic" (the xml : "xrr" is opaque to a human). Let's confer on Thurs. and confirm a decision, which we can then write up and put into our USEP Encoding instructions as a controlled vocab. list with principles for future additions as needed.

**Comment by jbodel** [comment]
image: there is one available at the Museum, so if we don't have one, we (Itamar) can request a digital file for editing.

**Comment by jbodel** [comment]
From our Encoding Instructions:

Language code: an abbreviated indication of the language (as opposed to the script) of the text, in most cases either “G” for “Greek” or “L” for “Latin”. (Other, less common, language codes include “E” for “Etruscan”, “Pun” for “Punic”, “Raet” for “Raetic”). In the case of bi- or tri-lingual texts, list the relevant language codes in order of presumed priority (e.g. “GL” or “LG”, depending upon context: see further below under “Summary”)
Note that the language as it appears in Author Mode is not the same as the information that is actually entered into the Epidoc file in Text Mode. The Author Mode value is intended to be clear to the person entering the inscription. The code that is entered into the Epidoc file is a universally recognized 3 letter language code.
Wherever possible, language codes in the metadata fields should use the closest relevant ISO-639 code (e.g. “phn”, “Phoenecian” for “Punic”, “arc” for all forms of ancient Aramaic). “und” (undetermined) is used to indicate an unknown language.

**Comment by sdigiulio** [comment]
OK -- I'll make these changes this weekend then.
We may wish to add [this link](https://iso639-3.sil.org/code_tables/639/data/all?title=&field_iso639_cd_st_mmbrshp_639_1_tid=All&name_3=&field_iso639_element_scope_tid=All&field_iso639_language_type_tid=31&items_per_page=200) somewhere in the encoding instructions, since it gives all current ISO codes for all ancient languages. Preference should be given to ISO-639-3.

**Comment by sdigiulio** [comment]
File still needs an image, which we should request; otherwise, ticket is completed and I will close.
