### ISSUE TITLE
possibly strange measurements in Kelsey inscriptions

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#184]
I was in the process of changing the Kelsey inscriptions that have unit="m" measurements for the dimensions of the object to "cm" by moving the decimal point 2 positions to the right. So `<height>0.04</height>` would become `<height>4</height>`
However, I've found some with extremely small measurements, and although in some cases they are fragments with just a few letters, so could be very small, others don't make sense. 

First, this is the query that find these in Oxygen:
`//dimensions[@type="surface"] [@unit="m"][ancestor::fileDesc[descendant::idno/@xml:id[starts-with(.,'MI.AA')]]]` as an XPath constraint in order to make sure that we are only searching in Kelsey inscriptions, and also that these numbers are within the `<dimensions>` element

Then `>0\d\.` as a search string to find all values that start with 0 and have only 1 other non-zero digit before the decimal point. (This is on my set of already converted measurements, so they should look like cm. ) in the files on github you'll find them with two extra decimal places on the left. )

Discounting the ones with very small depths, which makes sense for slabs, I am pasting the 46 very narrow or very short inscription IDs below. They may be fine, but perhaps a spot check would be helpful to make sure that the encoder didn't get their metric system confused. 
```
MI.AA.UM.KM.L.1005.xml: <height>03.2</height>
MI.AA.UM.KM.L.1005.xml: <width>03.8</width>
MI.AA.UM.KM.L.1042.xml: <width>05.5</width>
MI.AA.UM.KM.L.1069.xml: <width>09.2</width>
MI.AA.UM.KM.L.1073.xml: <width>07.4</width>
MI.AA.UM.KM.L.1411.xml: <height>07.3</height>
MI.AA.UM.KM.L.1413.xml: <height>07.3</height>
MI.AA.UM.KM.L.1414.xml: <height>05.8</height>
MI.AA.UM.KM.L.1417.xml: <height>06.4</height>
MI.AA.UM.KM.L.1422.xml: <height>06.5</height>
MI.AA.UM.KM.L.1423.xml: <height>09.7</height>
MI.AA.UM.KM.L.1426.xml: <height>06.8</height>
MI.AA.UM.KM.L.1427.xml: <height>09.2</height>
MI.AA.UM.KM.L.1428.xml: <width>02.8</width>
MI.AA.UM.KM.L.1432.xml: <height>09.7</height>
MI.AA.UM.KM.L.1433.xml: <height>05.8</height>
MI.AA.UM.KM.L.1434.xml: <height>06.5</height>
MI.AA.UM.KM.L.1436.xml: <height>07.8</height>
MI.AA.UM.KM.L.1437.xml: <height>06.2</height>
MI.AA.UM.KM.L.1529.xml: <height>09.6</height>
MI.AA.UM.KM.L.1530.xml: <height>07.6</height>
MI.AA.UM.KM.L.1560.xml: <height>06.4</height>
MI.AA.UM.KM.L.1560.xml: <width>01.2</width>
MI.AA.UM.KM.L.1563.xml: <height>09.1</height>
MI.AA.UM.KM.L.1563.xml: <width>08.7</width>
MI.AA.UM.KM.L.1564.xml: <height>06.8</height>
MI.AA.UM.KM.L.1566.xml: <height>05.5</height>
MI.AA.UM.KM.L.1567.xml: <width>08.6</width>
MI.AA.UM.KM.L.1569.xml: <height>07.3</height>
MI.AA.UM.KM.L.1574.r.xml: <height>08.6</height>
MI.AA.UM.KM.L.1574.r.xml: <width>09.9</width>
MI.AA.UM.KM.L.1574.v.xml: <height>08.6</height>
MI.AA.UM.KM.L.1574.v.xml: <width>09.9</width>
MI.AA.UM.KM.L.21412.xml: <height>02.5</height>
MI.AA.UM.KM.L.21412.xml: <width>03.5</width>
MI.AA.UM.KM.L.2456.xml: <width>06.9</width>
MI.AA.UM.KM.L.3052.xml: <width>09.2</width>
MI.AA.UM.KM.L.3059.xml: <width>06.8</width>
MI.AA.UM.KM.L.6718.xml: <height>03.3</height>
MI.AA.UM.KM.L.6718.xml: <width>02.4</width>
MI.AA.UM.KM.L.6808.xml: <height>05.8</height>
MI.AA.UM.KM.L.86.xml: <height>08.5</height>
MI.AA.UM.KM.L.886.xml: <height>09.5</height>
MI.AA.UM.KM.L.91916.xml: <width>04.1</width>
MI.AA.UM.KM.L.93475.xml: <width>04.6</width>
MI.AA.UM.KM.L.93476a-b.xml: <width>06.5, 07.8</width>
```

**Comment by emylonas** [comment]
There seem to be dimensions marked in meters also in Hammond Castle and Brooklyn Museum. At least, the unit attribute indicates "m" not "cm" Best to check and see if it's only the unit marker or the actual measurements.

**Comment by jbodel** [comment]
Thanks, Elli. I will check these (or spot check them) and will ask Sophia,
who has been working on the michigan collection, to keep her eye out also
for problems of this sort. Just to make sure I understand you: the list you
send here indicates the newly corrected measurements in cm., yes. So that
the first entry has a height of 3.2 cm, no. 2 a width of 3.8 cm, etc.

**Comment by jbodel** [comment]
That is likely. And probably elsewhere too. Sophia, can you please check
the HCM inscriptions? I will check BM when I can.

**Comment by emylonas** [comment]
The measurements in the list I include above are in cm. The Epidoc files on GitHub are still in meters. I've already converted the Kelsey files and can push the changes if it won't cause confusion. These are only the Kelsey inscriptions. I didn't convert Brooklyn Museum or HCM because I couldn't be sure if it was only an incorrect unit marker or incorrect measurements as well.

**Comment by sdigiulio** [comment]
I have a number of files waiting in the queue that need to be merged into
the main branch before you go ahead and make any major changes; I'll try to
get to them in the next few days, so let's not push the broad changes in
just yet.

**Comment by emylonas** [comment]
Will hold off

**Comment by sdigiulio** [comment]
All pending commits have been merged; you can go ahead with the bulk changes whenever you're ready now.

**Comment by emylonas** [comment]
Brooklyn Museum (many)
MA.Glouc.HCM.L.Tmp97.6.20
MA.Glouc.HCM.L.Tmp97.6.25
MA.Glouc.HCM.L.Tmp97.6.3-md
MA.Glouc.HCM.L.Tmp97.6.4-md
MA.Glouc.HCM.L.Tmp97.6.5-md
MI.AA.UM.KM.L.942

(search for these by looking for "m") no need to qualify.
