### ISSUE TITLE
Epidoc doesn't allow @resp on <div> or as a global attribute.

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#188]
file with a `@resp` on `<div type="commentary">` are invalid. It's a global TEI attribute but apparently not in EpiDoc.

**Comment by sdigiulio** [comment]
Can we enable this via customization? Otherwise, we'll need to figure out another way of indicating the responsibility for different sections in the meantime: `<resp>` under the `<respStatement>`?

**Comment by emylonas** [comment]
well, it's working now. No idea. Maybe some older files with hard coded schema? Closing
