### ISSUE TITLE
Invalid files

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#189]
I did a validation pass as I noticed some problems. some errors are older, but others more recent. I fixed some but it's getting late, so I'll share with the rest of you... 

For example:
MD.Balt.WAG.L.23.184, MD.Balt.WAG.L.54.176 Not valid - missing lots of </p> in the provenance elements, which for some reason had autocompleted as </placeName>also, there is an incorrect <date notBefore="0001" notAfter="0100" evidence="#unspecified">Apparently we only have "conjecture, external, Internal" as values for the @evidence attribute on <date>. Also, an incorrectly marked abbreviation.

Should we also have "unspecified" or is this "conjecture"? 
NY.Brook.BM.L.62.147.11 has provenance not in any element at all. Probably an early one that Itamar was just figuring out. 
KY.Lou.SAM.L.1929.17.326A-D has text inside a <gap>

More errors below. 
```
Il.Chi.UC.SMA.G.1967.115.284.xml: value of attribute "type" is invalid; must be an XML name

ITA.Rome.AAR.L.9339.xml: element "provenance" not allowed here; expected the element end-tag

KY.Lou.SAM.L.1929.17.326A-D.xml: text not allowed here; expected the element end-tag or element "certainty", "desc" or "precision"

KY.Lou.SAM.L.1929.17.351.xml: text not allowed here; expected the element end-tag or element "certainty", "desc" or "precision"

MD.Balt.JHU.L.BS.A.1181.xml: element "change" not allowed here; expected the element end-tag or element "encodingDesc", "profileDesc", "revisionDesc" or "xenoData"

MD.Balt.JHU.L.M.4.3.3.xml: value of attribute "target" is invalid

MD.Balt.JHU.L.M.7.3.1.xml: value of attribute "target" is invalid

MD.Balt.JHU.L.Tmp03.01.01.xml: value of attribute "target" is invalid

MD.Balt.WAG.G.23.175.xml: attribute "resp" not allowed here; expected attribute "ana", "change", "copyOf", "corresp", "decls", "exclude", "facs", "met", "n", "next", "org", "part", "prev", "real", "rend", "rendition", "rhyme", "sameAs", "sample", "select", "subtype", "synch", "xml:base", "xml:id", "xml:lang" or "xml:space"

MD.Balt.WAG.L.23.184.xml: value of attribute "evidence" is invalid; token "#unspecified" invalid; must be an XML name or must be equal to "conjecture", "external" or "internal"

MD.Balt.WAG.L.54.176.xml: element "hi" not allowed here; expected the element end-tag, text or element "add", "app", "corr", "del", "g", "handShift", "mod", "orig", "redo", "reg", "retrace", "sic", "supplied", "surplus", "unclear" or "undo"

MI.AA.UM.KM.L.1002.xml: value of attribute "hands" is invalid; must be an integer

MI.AA.UM.KM.L.817.xml: element "num" not allowed here; expected the element end-tag, text or element "add", "corr", "damage", "del", "g", "handShift", "mod", "orig", "redo", "reg", "retrace", "secl", "sic", "supplied", "surplus", "unclear" or "undo"

MI.AA.UM.KM.L.818.xml: element "num" not allowed here; expected the element end-tag, text or element "add", "corr", "damage", "del", "g", "handShift", "mod", "orig", "redo", "reg", "retrace", "secl", "sic", "supplied", "surplus", "unclear" or "undo"

MI.AA.UM.KM.L.840.v.xml: element "graphic" missing required attribute "url"

NJ.Princ.PU.AM.G.P3289-I37.xml: element "hi" not allowed here; expected the element 
end-tag, text or element "g"

NY.Brook.BM.L.62.147.11.xml: text not allowed here; expected the element end-tag or element "acquisition" or "provenance"

NY.NY.CU.Butl.L.37.xml: value of attribute "ana" is invalid

NY.NY.MMA.G.24.97.19.xml: value of attribute "ana" is invalid
```

**Comment by sdigiulio** [comment]
Working on these generally; the issue with `<date evidence="unspecified">` seems to be that that the attribute can only have those three values? Since it's clearly not looking at whether those values are coming from our taxonomy. We may need to reconsider our use of `@evidence` and find something that we can replace it with that allows for open values.

**Comment by sdigiulio** [comment]
Scratch the previous -- the issue was that we were validating against the wrong version of the schema for that particular error; updating the schema resolved the problem.

**Comment by sdigiulio** [comment]
Some of these errors are holdovers of the old includes for things like the publication statement, brought up in #156. All others addressed in https://github.com/sdigiulio/usep-data/commit/3dd824608300d35850d9ec68488992f9c5b6ffa6
