### ISSUE TITLE
MD.Balt.JHU.L.77 busted

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#19]
500 error on the collection again. not sure if its the bib or something else. File is valid other than having problems with @unit.

**Comment by emylonas** [comment]
I think it's this: <bibl type="e" xml:id="Libitina3">

Not sure if it should be an "m" or a "j" but I think I'll go with "m" for now.

**Comment by sdigiulio** [comment]
ah its the issue with libitina e dintorni. ill sort that out in a minute.

On Tue, Dec 8, 2015 at 5:41 PM, Elli Mylonas <notifications@github.com>
wrote:

> I think it's this:
>
> Not sure if it should be an "m" or a "j" but I think I'll go with "m" for
> now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brown-University-Library/usep-data/issues/19#issuecomment-163042739>
> .
>



-- 
Scott J. DiGiulio
Postdoctoral Fellow in Classics
Brown University
Department of Classics
Box 1856
Providence, RI   02912
Scott_DiGiulio@brown.edu

**Comment by emylonas** [comment]
done.
