### ISSUE TITLE
highlighted characters not indicated on website

### ISSUE THREAD

**Issue by spapando** [Brown-University-Library/usep-data#194]
Most types of highlighted characters, for example: `<hi rend="small">s</hi>`; `<hi rend="tall">t</hi>`; or `<hi rend="ligature">ae</hi>`, are not indicated in any way in the transcriptions on the website. I'm not sure how we should go about representing these characters, but I know `<hi rend="superscript">s</hi>` shows up on the website.

**Comment by sdigiulio** [comment]
My understanding is that this is an issue of editorial vs. diplomatic transcription; the features that you mention are not normally displayed in most print or digital editions when looking at an editorial transcription, and my instinct is that we wouldn't necessarily want to represent this visually in a transcription/edition. If we want to have more of a diplomatic display, we can consider that, but they're not normally something that is displayed in editorial format. If I'm mistaken on this, though, others should feel free to chime in.

**Comment by jbodel** [comment]
Yes, I agree that we do not want to try to render our transcriptions as
diplomatic text and so we should NOT display "superscript" characters
(which in any case has no meaning for the ordination of inscriptions) or
any other palaeographic features visually. We SHOULD however have 1) some
way of searching for / filtering the correctly encoded palaeographic
features and 2) some explicit verbal confirmation / record of the feature
in the beginning part (former "app. crit." div) of the Commentary section.
E.g.: "line 1: tall I in Dis / line 2: small in cos. 3) Ligatures: these
ARE normally represented in both print and digital transcriptions, with the
standard Pancierta-Krummrey sign of an apex mark (^) over the 2nd of two
letters in ligature, ad lib., so we SHOULD, if possible, indicate these in
our transcriptions.

**Comment by sdigiulio** [comment]
Ligatures and other features that do have representation in P-K should be built into EpiDoc and should be displaying properly already; if they're not, we can take a look at that when we update the version of EpiDoc we're using. In terms of searching/filtering, I know we index the features in the inscription, so one should be able to use the faceted search to locate, e.g., all instances of tall characters as long as they were marked up initially.

**Comment by sdigiulio** [comment]
After updating the stylesheets, it seems that the EpiDoc needs to be called correctly in order for these to display as desired, since the new xsl is currently transforming the texts appropriately. @emylonas and @sdigiulio (more or less) figured out where the changes need to be made on the code backend.

**Comment by sdigiulio** [comment]
Quick update: most features should now be displaying, with the exception of underlines. We're hoping to get this squared away with the css in the near future.

**Comment by sdigiulio** [comment]
Remaining issue (underlines) will be addressed in #221.
