### ISSUE TITLE
website homepage needs better labeling

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#199]
The correct name of the "U.S. Epigraphy Project" appears on our homepage only in the logo in the upper left, where some, at least, don't seem to recognize it. The map and list of collections are both "loosely" draft-labelled as "US Epigraphy", and this is the incorrect name by which the project is sometimes identified--as at epigraphy.info. 

The label texts need to be corrected. I suggest: 1) add banner title "U.S. Epigraphy Project"; 2) replace "US Epigraphy" with "USEP" in the two map labels.

**Comment by jbodel** [comment]
I was able to fix the label on the map itself but not the caption below providing a link to a full-screen map

**Comment by emylonas** [comment]
done, closed with e3a2eeaf0b09c1910300f40e0bd4769ac4891bed c4b04c05bf7b84550157f089c9fd0214b854141a
