### ISSUE TITLE
no bibliography

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#2]
These inscriptions have no bib at all. Either unpublished, or we don't have the ref yet. 

xml_inscriptions/transcribed/CA.Malibu.JPGM.G.79.AE.139.xml
xml_inscriptions/transcribed/CA.Malibu.JPGM.G.80.AE.99.3.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.11.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.13.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.14.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.15.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.15a.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.17.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.18.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.19.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.2.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.20.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.21.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.22.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.24.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.25.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.26.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.27.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.28.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.29.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.31.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.33.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.34.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.35.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.36.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.37.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.38.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.39.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.4.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.40.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.41.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.43.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.44.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.45.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.47.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.48.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.49.xml
xml_inscriptions/transcribed/MA.Glouc.HCM.L.Tmp97.6.9.xml
xml_inscriptions/transcribed/MI.AA.UM.KM.L.2004.1.1.v.xml
xml_inscriptions/transcribed/MI.AA.UM.KM.L.93880and93894and93896and1966.2.3--unpublished.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.03.6.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.08.480.108.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.151.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.154.1.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.154.2.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.320.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.359.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.440.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.580.99.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.633.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.656.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.16.90.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.28.769.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.34.678.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.34.690.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.37.1393E.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.40.301.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.41.684.xml
xml_inscriptions/transcribed/NY.Brook.BM.G.60.1.2.xml
xml_inscriptions/transcribed/NY.Brook.BM.L.16.105.xml
xml_inscriptions/transcribed/NY.Brook.BM.L.37.525.xml
xml_inscriptions/transcribed/NY.Brook.BM.L.62.147.10.xml
xml_inscriptions/transcribed/NY.Brook.BM.L.62.147.11.xml

**Comment by sdigiulio** [comment]
Fixed and committed all Brooklyn Museum, Kelsey Museum, and Hammond Castle entries missing bib data. Will fix Getty material once the folders are accessible.

**Comment by sdigiulio** [comment]
Fixed CA.Malibu.JPGM.G.80.AE.99.3.xml. Fixed CA.Malibu.JPGM.G.79.AE.139.xml, added note about its return to Italy in 2007. JB thinks we will eventually need to create a page for orphaned inscriptions like this that were once but are no longer housed in US collections.

**Comment by birkin** [comment]
hi scott, just an fyi in case you didn't know -- if you ever think it'd be useful for reference, you can insert into a comment like this a link to the commit, like this: <https://github.com/Brown-University-Library/usep-data/commit/538ff8395c29d7d29b94464a41bcc738535ef603> -- and the default view will show a nice short link.

**Comment by sdigiulio** [comment]
Thanks Birkin -- I'll make note of that for the future, especially for
fixes that don't really require more extensive notes.

On Fri, Jul 17, 2015 at 8:42 AM, Birkin James Diana <
notifications@github.com> wrote:

> hi scott, just an fyi in case you didn't know -- if you ever think it'd be
> useful for reference, you can insert into a comment like this a link to the
> commit, like this: 538ff83
> <https://github.com/Brown-University-Library/usep-data/commit/538ff8395c29d7d29b94464a41bcc738535ef603>
> -- and the default view will show a nice short link.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brown-University-Library/usep-data/issues/2#issuecomment-122262688>
> .
>



-- 
Scott J. DiGiulio
Postdoctoral Fellow in Classics
Brown University
Department of Classics
Box 1856
Providence, RI   02912
Scott_DiGiulio@brown.edu
