### ISSUE TITLE
MD.Balt.JHU.G.A.804 + MS.Univ.UM.UM.G.77.3.662 = Peek GVI 586?

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#205]
MD.Balt.JHU.G.A.804 is nicely transcribed (and translated etc.) and is correctly identified with (inter alia) Peek, GVI 586 but fails to indicate in the edition that the entire right half of the inscription is missing. In fact, this looks very much like a purposeful break down the middle of the slab. [The edition needs to be corrected to indicate where the break falls].

MS.Univ.UM.UM.G.77.3.662, for which we have "bibl. only", is also identified with Peek, GVI 586.  Is this the right half, originally one piece with MD.Balt.JHU.G.A.804? If so, when and how did it travel from Baltimore to Mississippi, and was it ever attested as fully intact (or with both pieces) at Johns Hopkins? We know that other inscriptions from that collection "wandered" to New York with Ralph Magoffin when he transferred to NYU. . . Were other pieces collected by Wilson similarly (or otherwise?) dispersed? Often the first element of a museum inventory number indicates the year of acquisition (as with our first-time-registered USEP entries for private collections). Maybe (19)"77" indicates the year of transfer?

A mystery for Scott, perhaps, who is looking into the MS. Univ.UM.UM collection, to investigate (in due course).

**Comment by sdigiulio** [comment]
After conversation with folks at U of Miss, the two are in fact halves of the same inscription; will continue tracking information on this down. My suspicion is that Robinson may have divided it when he moved institutions, but I would need to do more in terms of investigating to be sure.

In terms of the display to reflect the break, I think this is correct in the file; it should be corrected when the CSS is updated to use the most recent EpiDoc versions, which will be handled separately.

**Comment by jbodel** [comment]
I see the markup in the xml and don't know whether it is correct but nothing is displaying. Need CSS fix, not only here but in several other places where we have similar joins. I will try to collect these and comment in a separate issue.

**Comment by sdigiulio** [comment]
Previous editor markup now working thanks to CSS updates; closing this issue for the time being, as I'll get to the content-based portions once I edit the inscriptions from UMiss.
