### ISSUE TITLE
new entry: NJ.Princ.PU.AM.L.y1989-58

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#207]
Please add new entry:
text:   [Menerv]ai pocolom
date: 300-200 BCE

pdf with entry info and bibliography attached.
[NJ.Princ.PU.AM.L.y1989-58.pdf](https://github.com/Brown-University-Library/usepweb_project/files/5876797/NJ.Princ.PU.AM.L.y1989-58.pdf)

**Comment by sdigiulio** [comment]
@itamarle, you're not popping up in the assignments box but if you could handle this I'd appreciate it .
