### ISSUE TITLE
Need to format the Collection blurb at the top of the collections page! 

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#21]
the collections blurb is displaying with visible HTML tags, no formatting. This is coming from the django db. This is kind of urgent.

**Comment by crotger** [comment]
Opened a [PR](https://github.com/Brown-University-Library/projects-usep-app/pull/58) for this in the usep django project (not sure why this issue is in the data repo)

**Comment by emylonas** [comment]
apologies, my fault. --elli

[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]
