### ISSUE TITLE
Issue with bib data

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#22]
- No inscriptions references CIL_I, CIL_XVS, IGRR_I, Olcott_Catalogue, JHU_Gilman, JHU_Dunning and more perhaps
- AICAR_2008-9 in bib, AICAR_2008/9 IL.Chi.AIC.G.2009.76.xml

I guess we should do a quality control check and also a check to see what is used and what isn't 

journals aren't working because of article titles I think - will pub issue into other USEP git

**Comment by sdigiulio** [comment]
- Fixed AICAR issue
- Olcott, Gilman, Dunning are catalogs for individual collections, can possibly be removed?
- Will look into others.

**Comment by emylonas** [comment]
Maybe the solution is to figure out what to do when there are no inscriptions associated with a publication? but if a publication isn't associated with an inscription, then it isn't really there.

The page could just have a better message when there are 0 hits.

**Comment by sdigiulio** [comment]
Part of #25

**Comment by sdigiulio** [comment]
This should be a relatively quick fix, but will be folded in with the larger bibliography sprint planned for later in the spring.

**Comment by sdigiulio** [comment]
For the time being this seems to be resolved; closing for now but can readdress if there are additional problems.
