### ISSUE TITLE
new collection: RI.Prov.BU

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#231]
For Itamar: here are two images for a new entry:  RI.Prov.BU.G.21.04.01-mdn 
and a new collection: RI.Prov.BU.
Please make a new collection entry with this collection description: "The Department of Classics at Brown University has a small collection of squeezes of Greek inscriptions and currently houses in MacFarlane House a plaster cast of a Greek grave relief."
Once the inscription is IDed (for making the photo label and entry) we can add a little more.

[I decided to leave the collection designation as simply "BU", to allow the various subcollections of squeezes ("sq"s) and "-mdn"s to be accommodated under it. We have subcollections broken out for Princeton but generally not elsewhere.]

![RI Prov BU G 21 04 01-mdn](https://user-images.githubusercontent.com/16357617/114772213-8b433180-9d3b-11eb-8360-1682c53a1106.jpg)
![RI Prov BU G 21 04 01-mdn-det](https://user-images.githubusercontent.com/16357617/114772252-96965d00-9d3b-11eb-94ec-48ca3c41aaa3.jpg)

**Comment by sdigiulio** [comment]
Collection has been created, as has first file; updates and corrections to be done ad hoc.
