### ISSUE TITLE
 evidence="previouseditor" not displaying

### ISSUE THREAD

**Issue by spapando** [Brown-University-Library/usep-data#244]
Currently, there is no visible indication on the website that a portion of a transcription is supplied based on a previous edition, e.g. [MI.AA.UM.KM.L.1448](https://usepigraphy.brown.edu/projects/usep/inscription/MI.AA.UM.KM.L.1448/) and [CA.Berk.UC.HMA.L.Tmp97.3.3](https://usepigraphy.brown.edu/projects/usep/inscription/CA.Berk.UC.HMA.L.Tmp97.3.3/)

**Comment by sdigiulio** [comment]
This is an issue that we've been aware of and is part of #205; it will be resolved once that issue is cleared.

**Comment by sdigiulio** [comment]
CSS problem now fixed in https://github.com/Brown-University-Library/usepweb_project/pull/78.
