### ISSUE TITLE
St. Louis Museum Collection Error

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#251]
Since we have changed the code for the St. Louis museum material in the files, we also need to make the change in the admin section of django in order to have the collection display properly. I'd do this myself but I don't have access to that part of the page.

**Comment by emylonas** [comment]
This has been updated in the Admin interface. The code for the Art Museum in St. Louis is MO.SL.CAM - and there is one transcribed file in the XML files. Should there be more?

**Comment by jbodel** [comment]
For now this is all we have.

**Comment by jbodel** [comment]
Also, since we have only the one piece and the museum has changed names and
uses its new acronym SLAM, we should update the collection code to
MO.SL.SLAM.

**Comment by emylonas** [comment]
There is also no short description of the museum and collection.

**Comment by jbodel** [comment]
I will do this.

**Comment by emylonas** [comment]
Actually, that was a mistake, and I deleted the comment. Apologies. There
is a brief description.

[Sent from my phone, please excuse fumbles and autocorrect.]

**Comment by jbodel** [comment]
Good--no problem! One less thing ot do is never a problem!

**Comment by emylonas** [comment]
Done. Closing with e35c39ee8b6c6884ef927fd4dc451a7b469fb498
