### ISSUE TITLE
CA.Malibu.JPGM.L.84.AN.I.62

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#26]
CA.Malibu.JPGM.L.84.AN.I.62 appears in search on Worfdev; I think needs to be cleared from index, since file is not in Git (appears to be old mistake for CA.Malibu.JPGM.L.84.AN.1.62, which is now in transcribed folder)?

**Comment by sdigiulio** [comment]
This is still popping up in solr queries, even though it isn't in the git folder.

**Comment by emylonas** [comment]
seems to have been fixed. closing
