### ISSUE TITLE
remove NoImage.jpg from facsimile

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#31]

**Comment by sdigiulio** [comment]
Do we want this to be moved over to the 'NoImageAvailable.jpg' file
instead? If so I can batch update those.

**Comment by emylonas** [comment]
I think not, better to have no fake file at all. But this is more of a placeholder for now. Are there 3 cases? NoImage.jpg, NoImageAvailable.jpg and blank?
