### ISSUE TITLE
Display authorship

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#34]
Should look into adding display of the responsible parties (from change log?) on individual pages. I think this can be handled via the xsl, but we'll need to think about what info to display and how.

**Comment by jbodel** [comment]
For files, the method of display used by EDR seems good. Author and date. Maybe:
"File edited by: XXX" on "YYYY-MM-DD"

For quoted material (if other than by file editor), maybe indicate at the end of the commentary simple AUTHOR SURNAME + 'short title' (presumably the source of the information will be indicated in the bibliog. or else will be "museum records" or the like)?

**Comment by sdigiulio** [comment]
This should now be addressed in the xsl with commit 4015c2859f297536b14fc499a59215bf3f3561de; @emylonas if anything else needs to be changed to fix this let me know. Otherwise I'll close the issue.

**Comment by sdigiulio** [comment]
Still not working right -- @sdigiulio will continue to implement.

**Comment by sdigiulio** [comment]
Updates in eb61f58f, dc42392f; code is now valid, but table for display is not appearing on page.

**Comment by emylonas** [comment]
This is being handled in #55
