### ISSUE TITLE
Women's Colleges Xml

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#4]
Per JB, top priority in entering new material at present is getting the material from the women's colleges up on the site. Most need to be encoded from scratch off of the hard-copy material.

**Comment by emylonas** [comment]
Scott, make sure to check the old site, there were a few there that didn't make it over

**Comment by sdigiulio** [comment]
There are a handful, yes; do you have a sense of where the files would be
for those? I didn't see them in the shared drive (though I didn't burrow
through everything that's there). On the other hand I could do the rest
over using new template/schema, which might not be the worst thing in the
world.

On Fri, Jul 17, 2015 at 3:55 PM, Elli Mylonas <notifications@github.com>
wrote:

> Scott, make sure to check the old site, there were a few there that didn't
> make it over
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brown-University-Library/usep-data/issues/4#issuecomment-122394450>
> .
>



-- 
Scott J. DiGiulio
Postdoctoral Fellow in Classics
Brown University
Department of Classics
Box 1856
Providence, RI   02912
Scott_DiGiulio@brown.edu

**Comment by emylonas** [comment]
Best bet is to use any HTML info from the originals and redo in epidoc. But
I can send them to you if you tell me what files you want.

**Comment by sdigiulio** [comment]
In that case don't worry about it, I'll work through everything fresh off
the paper folder materials

On Fri, Jul 17, 2015 at 4:34 PM, Elli Mylonas <notifications@github.com>
wrote:

> Best bet is to use any HTML info from the originals and redo in epidoc. But
> I can send them to you if you tell me what files you want.
>
> On Fri, Jul 17, 2015 at 4:31 PM, sdigiulio <notifications@github.com>
> wrote:
>
> > There are a handful, yes; do you have a sense of where the files would be
> > for those? I didn't see them in the shared drive (though I didn't burrow
> > through everything that's there). On the other hand I could do the rest
> > over using new template/schema, which might not be the worst thing in the
> > world.
> >
> > On Fri, Jul 17, 2015 at 3:55 PM, Elli Mylonas <notifications@github.com>
> > wrote:
> >
> > > Scott, make sure to check the old site, there were a few there that
> > didn't
> > > make it over
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Brown-University-Library/usep-data/issues/4#issuecomment-122394450
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Scott J. DiGiulio
> > Postdoctoral Fellow in Classics
> > Brown University
> > Department of Classics
> > Box 1856
> > Providence, RI 02912
> > Scott_DiGiulio@brown.edu
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Brown-University-Library/usep-data/issues/4#issuecomment-122404208
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brown-University-Library/usep-data/issues/4#issuecomment-122405052>
> .
>



-- 
Scott J. DiGiulio
Brown University
Department of Classics
Box 1856
Providence, RI   02912
Scott_DiGiulio@brown.edu

**Comment by sdigiulio** [comment]
xml written, waiting on proofread (and possibly images?) before upload

**Comment by sdigiulio** [comment]
Uploaded, will sort out images separately
