### ISSUE TITLE
Links to XML on Git not appearing correctly on website

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#48]
The link to the source xml of individual files on the USEP main site is not displaying correctly -- need to a) correct the image path so that it displays the correct image and b) add a line of text indicating what the link goes to.

**Comment by emylonas** [comment]
@sdigiulio do you still want to add a line of text that says "View XML" or can we close the isuse?

**Comment by sdigiulio** [comment]
The icon we picked is I think self-explanatory enough; I'm not sure we need the line of text, so I think we can close this for now.
