### ISSUE TITLE
New Top-Level

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#54]
A new top-level identifier for country will need to be created; once it is set up, file names will need to be updated (@sdigiulio ) and we will need to ensure that there are no other issues in the underlying code.

**Comment by emylonas** [comment]
At the moment we are handling this by treating Italy as a state: ITA.Rome... Adding a  new country at the top level, and adding US to all the current ids is a much bigger task, and not needed right now. We will work on it later.

**Comment by emylonas** [comment]
Discussed by @jbodel @sdigiulio @gaiagianni @emylonas on April 23, this solution is fine. No need to do anything at this point, or perhaps ever.

**Comment by emylonas** [comment]
closing. If issues arise, we can re-open
