### ISSUE TITLE
Errors in Dating

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#56]
Large number of files erroneously only list dates as 1st-2nd century; the data needs to be fixed.

**Comment by sdigiulio** [comment]
My understanding is that much of this has been addressed with @spapando's metadata updates throughout the Michigan collection; if we could confirm this, I'll close the ticket.

**Comment by spapando** [comment]
I have gone through and double-checked and updated dates. If it hasn't been corrected yet, I'll get there at some point.

**Comment by sdigiulio** [comment]
This sounds good to me; I'll close the issue and as we'll continue correcting this information as we encounter it.
