### ISSUE TITLE
New field for reasoning for date

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#59]
Would like to add a field explaining the reasoning for assigning a particular date. Will require a basic control vocabulary to be developed.

@emylonas this can likely can be done using `@datingMethod` vel. sim., no?

**Comment by jbodel** [comment]
Basic control vocabulary is as follows (from email of 9/1/2018):
history    [i.e. reference to some historically dated event, such as a consulship or battle]
archaeology   [i.e. archaeological context or material --e.g. tufa ]
institutions     [i.e. something like Augustales, or certain collegia]
formulae        [e.g. 'D. M.']
prosopography      [form of name and individual elements--some overlap with 'history' in imperial titles]
palaeography

**Comment by sdigiulio** [comment]
The standard way to add this information is to start adding `@evidence` using a control vocabulary: (http://www.stoa.org/epidoc/gl/latest/supp-historigdate.html) also has some suggestions for vocabulary, should we want to go with what is already standard. 

Next steps would be:
* Add field to template for encoders to record data
* Add whatever control vocabulary we want to use to the main vocabularies
* If we want this reason to display, tweak XSLT to enable display

**Comment by sdigiulio** [comment]
Began writing control vocab to incorporate these features in 44d731cc; will need to continue fleshing this out and potentially adding .xsl features to display the reasoning.

**Comment by emylonas** [comment]
closing as this is being handled in #112
