### ISSUE TITLE
MA.North.SC Collection Issues

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#7]
Clicking on the collection from the main page triggers a 500 server error; also, can't bring up MA.North.SC.L.87.52 which was updated today.

**Comment by birkin** [comment]
will look into this later today. -b

**Comment by birkin** [comment]
- re the 500 server error, the [CA.Malibu.JPGM](http://library.brown.edu/projects/usep/collections/CA.Malibu.JPGM/) also raises a 500 error.
- logs indicate a problem with accessing an expected solr field 'msid_idno' that it looks like every solr doc should have, but perhaps some don't.
- out today but will work on getting project running on hm machine and investigate more; otherwise more tomorrow am.

**Comment by birkin** [comment]
hmm... just checked all the [MA.North.SC solr records](http://library.brown.edu/search/solr_pub/usep/?rows=20&facet=true&facet.limit=1000&facet.mincount=1&start=0&facet.field=bib_ids&f.bib_ids.facet.sort=false&facet.field=bib_ids_filtered&f.bib_ids_filtered.facet.sort=false&facet.field=bib_titles&f.bib_titles.facet.sort=false&facet.field=condition&f.condition.facet.sort=false&facet.field=decoration&f.decoration.facet.sort=false&facet.field=fake&f.fake.facet.sort=false&facet.field=text_genre&f.text_genre.facet.sort=false&facet.field=language&f.language.facet.sort=false&facet.field=material&f.material.facet.sort=false&facet.field=msid_region&f.msid_region.facet.sort=false&facet.field=msid_settlement&f.msid_settlement.facet.sort=false&facet.field=msid_institution&f.msid_institution.facet.sort=false&facet.field=msid_repository&f.msid_repository.facet.sort=false&facet.field=object_type&f.object_type.facet.sort=false&facet.field=status&f.status.facet.sort=false&facet.field=writing&f.writing.facet.sort=false&q=%2A%3A%2A&fq=msid_region%3A%22MA%22&fq=msid_settlement%3A%22North%22&fq=msid_institution%3A%22SC%22&sort=&wt=json&json.nl=arrarr) and the [CA.Malibu.JPGM solr records](http://library.brown.edu/search/solr_pub/usep/?rows=200&facet=true&facet.limit=1000&facet.mincount=1&start=0&facet.field=bib_ids&f.bib_ids.facet.sort=false&facet.field=bib_ids_filtered&f.bib_ids_filtered.facet.sort=false&facet.field=bib_titles&f.bib_titles.facet.sort=false&facet.field=condition&f.condition.facet.sort=false&facet.field=decoration&f.decoration.facet.sort=false&facet.field=fake&f.fake.facet.sort=false&facet.field=text_genre&f.text_genre.facet.sort=false&facet.field=language&f.language.facet.sort=false&facet.field=material&f.material.facet.sort=false&facet.field=msid_region&f.msid_region.facet.sort=false&facet.field=msid_settlement&f.msid_settlement.facet.sort=false&facet.field=msid_institution&f.msid_institution.facet.sort=false&facet.field=msid_repository&f.msid_repository.facet.sort=false&facet.field=object_type&f.object_type.facet.sort=false&facet.field=status&f.status.facet.sort=false&facet.field=writing&f.writing.facet.sort=false&q=%2A%3A%2A&fq=msid_region%3A%22CA%22&fq=msid_settlement%3A%22Malibu%22&fq=msid_institution%3A%22JPGM%22&sort=&wt=json&json.nl=arrarr) and they do all have the msid_idno field filled out. Will investigate more.

**Comment by birkin** [comment]
Ok, i see the problem. Let's focus on `MA.North.SC`. The actual solr call, and records returned, is not as I indicated in the previous comment. The call and returned results are more like [this](http://library.brown.edu/search/solr_pub/usep/?rows=99000&indent=on&q=MA.North.SC&start=0&wt=json&fl=id%2Cstatus%2Cgraphic_name%2Clanguage%2Cmsid_idno).

...Which shows the issue. The code expects every solr record to have an msid_idno field.

There are various ways I can handle this -- but one possibility is to look at the data to if there is an obvious reason the `MA.North.SC.L.87.52` and `MA.North.SC.L.54-54a` records are missing an id field.

Also, note that other collections having the same issue can be inspected by using the above url, substituting the problematic collection's id with `MA.North.SC`.

**Comment by emylonas** [comment]
MA.North.SC.L.54-54a had element content of "NL" on msIdentifier/repository . This isn't part of the  USEP id. Seems that the indexing process using the components of the msIdentifier  was unable to function properly with this, which kept the inscription from being indexed, and broke the collection page view.

Now you can see the collection page, but only some of the Smith inscriptions are showing.

**Comment by emylonas** [comment]
a few Smith inscriptions are showing. no more 500 Error on collection view. Things to look for:
1. if there are validation problems, id inconsistencies or missing xml extensions, it's likely that the collection view won't work. Look for problems in the files
2. If an inscription isn't showing up, check validation and then check the browser console error log to see if there are xsl fatal errors.
