### ISSUE TITLE
EpiDoc files +images not loading

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#73]
VA.GladeSpring.PHHS -- data not loading

**Comment by sdigiulio** [comment]
Everything is present in Git, so this is likely an indexing issue. @emylonas, I think you were going to talk to Birkin about this -- any update?

**Comment by emylonas** [comment]
USEP isn't indexing. This is a known problem and I hope that it will be fixed this week if not fixed already. This is for texts.
I also asked that the whole of USEP be re-indexed so that it picks up all changes that have been added since indexing broke.

**Comment by sdigiulio** [comment]
Since the particular collection in question is now behaving as expected, closing the issue.
