### ISSUE TITLE
new collection: MA.Newt.Gulotta

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#77]
Please open a new collection for MA.Newt.Gulotta. One opisthographic inscription for which I now have photos to edit.

**Comment by emylonas** [comment]
We had MA.Newt.priv with a description of the Gulotta inscription in its about section.  I changed it to MA.Newt.Gulotta. Should be visible on the main page.

**Comment by jbodel** [comment]
Aha, thanks. The MA.Newt Gulotta is not listing correctly with the others from MA b/c the heading naming the state is misspelled: One S in second position and two Ts:  "Massachusetts". Please fix

**Comment by emylonas** [comment]
corrected and closed
