### ISSUE TITLE
consistency in form of collection addresses

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#78]
A small issue noticed in the listing of the addresses of MA collections but evidently scattered throughout: some addresses write out the name of the state in full (Massachusetts), others (a majority) use the US postal code (which I think helps those not as familiar with our US state codes to recognize the state abbreviation as the same as the 1st element in the USEP number).

I propose that we regularize the form by converting ALL state addresses to the US postal code abbreviation -- here "MA". 

Is this the kind of work Gaia can do? I don't know if I (and eventually she) have access to those pages on GitHub.

**Comment by emylonas** [comment]
definitely work that Gaia can do. The database is accessible by password
and needs one to authenticate with Brown credentials, as well.

**Comment by jbodel** [comment]
Please do this or have Sophia do this

**Comment by gaiagianni** [comment]
I changed all the addresses that featured the full name of the state, now they all have the state two-letter abbreviation. I do still have one question though. The use of commas is not consistent, sometimes the state abbreviation and zip code are separated by a comma, sometimes not.
Do you have a particular format that you prefer John?

**Comment by jbodel** [comment]
Thanks, Gaia! Good query re commas. A quick check through all the states suggests that we more often did NOT use a comma after the state code (before zip code), so let's make that the standard throughout.

**Comment by gaiagianni** [comment]
Okay, great, I will be done with it soon.

**Comment by gaiagianni** [comment]
Done. I am closing the issue now.
