### ISSUE TITLE
files missing xml extension perhaps causing problems

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#8]
Scott - for you, to check in case they should be eliminated or are otherwise duplicated.

transcribed/MA.Camb.HU.Sack.G.2003.97
transcribed/MI.Detr.DIA.G.75.14
transcribed/VA.Williamsb.WMU.08.3.1

**Comment by sdigiulio** [comment]
Fixed; I wrote these recently and accidentally dropped the extension. No duplicates, pushing them back with corrected filenames.
