### ISSUE TITLE
check Sackler inscriptions 

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep-data#83]
These seem to be messed up. Many should have been transcribed but they are either "metadata only" or "bib only" in the USEP github repo.

**Comment by sdigiulio** [comment]
Need to check for previous versions of the files; all the files currently in the repo are filed correctly according to their level of markup. Given that there are labeled images for many of those that are currently metadata-only (and which were worked on in 2016), fairly sure that there likely were at some point transcriptions for these files.

In the absolute worst case, I can write new transcriptions for all of those.

**Comment by sdigiulio** [comment]
Pending locating any old files, will bump this to next on the docket for new editing work.

**Comment by sdigiulio** [comment]
I've completed these and re-posted them.
