### ISSUE TITLE
Advanced Search: controlled vocabularies need editing

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#89]
In Advanced search, all lists of controlled vocabulary terms need editing to eliminate duplication, idiosyncratic non-standard terms. I will provide correct lists as soon as Elli or Scott is prepared to fix the current blocks

**Comment by sdigiulio** [comment]
Most of these should be populating directly from the existing master control vocabulary and whatever values are found in the files themselves; I remember doing a pretty extensive cleaning of these some years ago. Any values that don't align with the control vocabulary can be edited directly in the files in which they're found, and once they're changed they should disappear from the search.

The one place where there is not an existing vocabulary is for the special characters; at the moment we're pulling directly from the files.

**Comment by jbodel** [comment]
Thanks, Gaia and I can then begin searching and replacing the wayward terms in order to "control" the lists.

**Comment by sdigiulio** [comment]
Connected to #29

**Comment by emylonas** [comment]
Search is not working overall, issue on this is in code issues, https://github.com/Brown-University-Library/usepweb_project/issues/6
