### ISSUE TITLE
MA.Newt.Gulotta collection not loading -- neither images nor metadata

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#91]

**Comment by emylonas** [comment]
It has to do with the name change, I'll ask someone to force the re-indexing.

**Comment by emylonas** [comment]
@jbodel there was a mistake in the filenames (`Ma` not `MA`) so file wasn't found. The files are visible now. Pls check. The home page took a while to load and that was odd.

**Comment by jbodel** [comment]
Aha--thanks!
