### ISSUE TITLE
display of Greek too tight

### ISSUE THREAD

**Issue by jbodel** [Brown-University-Library/usep-data#98]
Character spacing between Greek letters and (less so) between lines of Greek are too tight, need to be expanded. Notable recent example IN.Crawf.LWSR.G.17.

**Comment by sdigiulio** [comment]
This is probably related to the css/the font we use, right @emylonas? If so, best to tackle as part of other edits we're planning to make to the display.

**Comment by sdigiulio** [comment]
Should now be addressed in https://github.com/Brown-University-Library/usepweb_project/pull/75; closing for now.
